schema_version = "1.0.0"

id = "PieMenusPlus"
version = "1.4.3"
name = "Pie Menus Plus"
tagline = "Improved Pie Menu ecosystem for Blender 2.8-5.0 and beyond"
maintainer = "Ethan Simon-Law <ethan.simon.3d@gmail.com>"
type = "add-on"

website = "https://discord.com/invite/wHAyVZG"

tags = ["3D View",]

blender_version_min = "4.2.0"

license = [
  "SPDX:GPL-3.0-or-later",
]
